### ISSUE TITLE
Some bugs on 8.18

### ISSUE THREAD

**Issue by RacquelSilverSpirit** [ByzantineFailure/BPM-for-Discord#62] opened 2017-01-13 22:11 UTC
Hello.

I have installed the latest pre-release plugin discord-v0.8.18 for the latest version of better discord. The plugin loads up but now there is no BPM tab under better discoed as normal so can not edit or change any settings. there is a default sweetie belle icon for the search tab but without this BPM tab under better discord nothing can be edited or changes in this plugin sorry. I'm also using a custom theme that requires me to move the search box for it to be seen. I hope this will help. Thank you for taking your time to read this.
![missing bpm tab](https://cloud.githubusercontent.com/assets/25110534/22147027/92fa0efe-df52-11e6-804c-777af5777666.PNG)

**Comment by ByzantineFailure** [comment] 2017-01-22 19:45
You definitely opened this earlier than #65 , but I'm going to close this as a duplicate of it given that it has some discussion on it already.  Looking into this!

**Closed as completed by ByzantineFailure** 2017-01-22 19:45 UTC

**Comment by ByzantineFailure** [comment] 2017-01-22 21:03
See #65 for resolution.
