### ISSUE TITLE
Settings tab not showing up in main settings menu (BPM for BD)

### ISSUE THREAD

**Issue by Kekerin0** [ByzantineFailure/BPM-for-Discord#65] opened 2017-01-22 03:21 UTC
Everything else about the plugin seems to work.  I can search and add emotes.  The sbstare is displayed at the bottom of my servers.  But I can not change any settings because the settings tab is gone

![image](https://cloud.githubusercontent.com/assets/25274722/22179643/fa3f85d2-e027-11e6-9ef7-92043959d047.png)

**Comment by Shugabuga** [comment] 2017-01-22 15:17
Are you using macOS or Windows? macOS has two ways to enter Settings, and I recall one used to be broken until recently (so maybe it broke again?).

**Comment by ByzantineFailure** [comment] 2017-01-22 19:46
Blech, okay, looks like I'm gonna have to install BD and try to figure out why this is happening.  *grumble*

Note, this happens on Windows BD as well.

**Comment by ByzantineFailure** [comment] 2017-01-22 20:13
From what I can tell this is due to a change in BetterDiscord -- I think it actually does some re-naming or... _something_ of the entire settings modal which prevents BPM's `MutationObserver from functioning.

**Comment by ByzantineFailure** [comment] 2017-01-22 20:16
Confirmed.  I kept the old button-listener-based implementation around in comments and it seems to have paid off -- definitely works with BD when I don't use the `MutationObserver`.  Unfortunately reverting to that implementation means that the Mac `Preferences` selector is broken for vanilla BPM and I'm not willing to break vanilla BPM for BD.

So, I need to figure a thing to listen on for BD specifically, and it's likely going to impact performance.  Neat.

Side note, I'm getting _real_ sick of BD continually breaking shit.

**Comment by ByzantineFailure** [comment] 2017-01-22 20:55
Fixed via 07295325d1595d8625d46ef8666f3e63f5558193

I'm not going to push this out immediately.  Given the rate at which BD has been breaking shit lately I want to wait at least a week to see if anything else breaks before pushing out a BD-specific pre-release.

This issue will remain open until a release is pushed out.

**Comment by ByzantineFailure** [comment] 2017-02-01 01:03
Released.  Closing.

**Closed as completed by ByzantineFailure** 2017-02-01 01:03 UTC
